#!/usr/bin/env bash
# installs nginx web server on your server and do some stuff with its configurations

sudo apt update
sudo apt install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart

sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
	listen 80;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm;
	location /redirect_me {
        	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF
sudo service nginx restart
