#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

# installing HAproxy PPA
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y

# updating
sudo apt update
sudo apt upgrade -y

# installing HAproxy
sudo apt install -y haproxy

sudo service haproxy start

sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup  # Backup existing config
sudo touch /etc/haproxy/haproxy.cfg  # Create a new config file

HAproxy_conf="\
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 376721-web-01 18.204.7.111:80 check
    server 376721-web-02 100.26.213.167:80 check
"

echo "$HAproxy_conf" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
