#!/usr/bin/env bash
# 4 is bad luck, 8 is good luck and anything else is Best School
count=1
while [ $count -le 10 ]; do
	if [ $count -eq 4 ]; then
		echo "bad luck"
	elif [ $count -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	count=$((count+1))
done
